"""Shipped text is written for a user of this package, not for a reader of the research record.

The research repository, its claim ids and its retired artifact are not things a user can open,
so no shipped file names them. `docs/verification.md` is a dated record of the port and
`docs/superpowers/` holds development documents; both are exempt. So are a notebook's recorded
outputs: they are a dated record of a run with the since-retired artifact, which a markdown cell at
the top of each notebook says, and they are not regenerated by hand. A notebook's cell sources are
what a user runs and reads, and they are scanned like any other file.
"""
import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

#: Where shipped text lives. Tasks that sweep more of the tree extend this.
SCANNED_ROOTS = ["lfa", "README.md", "RELEASING.md", "docs", "examples"]

EXEMPT = {"docs/verification.md"}
EXEMPT_DIRS = {"docs/superpowers", "__pycache__", ".worktrees"}
SUFFIXES = {".py", ".md", ".yaml", ".yml", ".toml", ".txt", ".ipynb", ".in"}

#: Built by parts so this file does not match itself.
FORBIDDEN = [
    ("a research claim id", re.compile(r"\bC1[0-9]\b")),
    ("the research record", re.compile(r"\bthe LFA " + r"record\b", re.IGNORECASE)),
    ("the research repository", re.compile("mr-" + "fusion")),
    ("the retired published artifact", re.compile("gmm" + "1543k")),
    ("the retired --artifact-id flag", re.compile("--artifact" + "-id")),
]


def _shipped_files():
    for root in SCANNED_ROOTS:
        base = REPO_ROOT / root
        paths = [base] if base.is_file() else sorted(base.rglob("*"))
        for path in paths:
            relative = path.relative_to(REPO_ROOT).as_posix()
            if (not path.is_file() or path.suffix not in SUFFIXES or relative in EXEMPT
                    or any(relative == d or relative.startswith(d + "/") or f"/{d}/" in relative
                           for d in EXEMPT_DIRS)):
                continue
            text = path.read_text(encoding="utf-8", errors="replace")
            if path.suffix == ".ipynb":
                for index, cell in enumerate(json.loads(text)["cells"]):
                    yield f"{relative} cell {index}", "".join(cell["source"])
            else:
                yield relative, text


def test_no_shipped_file_speaks_in_the_research_records_terms():
    hits = []
    for relative, text in _shipped_files():
        for number, line in enumerate(text.splitlines(), 1):
            for label, pattern in FORBIDDEN:
                if pattern.search(line):
                    hits.append(f"{relative}:{number}: {label}: {line.strip()[:100]}")
    assert not hits, "\n".join(hits)


def test_a_notebooks_sources_are_scanned_and_its_recorded_outputs_are_not():
    scanned = dict(_shipped_files())
    cells = [key for key in scanned if key.startswith("examples/two_domain_walkthrough.ipynb cell ")]
    assert cells, "the walkthrough's cells are not being scanned"
    assert any("Workspace.init" in scanned[key] for key in cells)
    # printed by the artifact cell's recorded run, so it is in an output and in no source
    assert not any("112.8 MB" in scanned[key] for key in cells)


def test_the_scan_sees_a_planted_hit(tmp_path, monkeypatch):
    planted = REPO_ROOT / "lfa" / "_planted_for_the_wording_test.py"
    planted.write_text("# see C12 in mr-" + "fusion\n")
    try:
        hits = [rel for rel, text in _shipped_files() if "C12" in text]
        assert "lfa/_planted_for_the_wording_test.py" in hits
    finally:
        planted.unlink()
