#!/usr/bin/env python3
"""Three domains in a row: train, fold in, train, fold in, train.

This is the continual flow of Layerwise Function Anchoring (LFA). One call --
:meth:`lfa.Workspace.chain` -- runs the whole sequence from ``examples/domains.yaml``, and what
it does between stages is the part that matters:

* the stage's adapter is merged into the model it was trained over, so the next stage adapts
  ``base + A`` rather than ``base``;
* the domain it just learned is added to the p(h) artifact as a small mixture in the base's own
  basis, weighted by sample share, so the next stage's anchor prices the function on the hidden
  states the *current* model visits;
* from stage 2 on, lambda is multiplied by the recipe's ``stage2_lambda_multiplier``.

Nothing from an earlier domain is stored or replayed: only the new domain is ever read, and each
round adds a fixed number of mixture components, so the cost per round does not grow with the
number of rounds.

**The corpora are generated, not downloaded.** So that the example runs offline and writes
nothing next to the spec, each domain named in the spec gets a small synthetic stand-in written
under ``--out/corpora/<name>``, and a copy of the spec pointing at those is what actually runs.
The text is filler -- it is there to exercise the machinery, not to teach a model anything. Point
the spec's ``corpus`` fields at real documents (and drop ``--epochs``) to run it for real.

Every number this prints is computed locally. Nothing calls out to a model API.

Example::

    python examples/chain_three_domains.py \\
        --model Qwen/Qwen3-0.6B \\
        --artifact qwen3-0.6b-gmm1543k-int8 \\
        --out runs/three_domains

``--artifact`` also takes a path, which is what to pass while the published assets do not exist
yet: fetching by id refuses until the registry's checksums are filled in (see ``RELEASING.md``).
A chain needs ``--artifact-id`` beside it -- ``--artifact /path/to/distribution_stats.pt
--artifact-id qwen3-0.6b-gmm1543k-int8`` -- because the step between two domains reads the base
sample count from the registry entry when the artifact carries none, as the shipped one does;
without it the first ``extend`` refuses after the first stage has already trained.
"""

from __future__ import annotations

import argparse
import json
import logging
import random
from pathlib import Path

import yaml

from lfa import Workspace

DEFAULT_SPEC = Path(__file__).parent / "domains.yaml"

#: Sentence frames the synthetic corpora are built from. They are deliberately about this
#: package rather than about the domain they are filed under: nothing here is real domain text,
#: and a reader who opens one of the generated files should be able to tell that at a glance.
_FRAMES = (
    "In {topic}, a document is only ever read once by the loader that chunks it.",
    "The {topic} corpus in this file is synthetic filler generated by the chain example.",
    "Anchoring compares teacher and student outputs of a sub-module on states drawn from p(h).",
    "A {topic} stage adds its own mixture components to the artifact when it is folded in.",
    "Nothing from an earlier domain is replayed while {topic} is being learned.",
    "The weight term is a backstop for the drift the function anchor does not price.",
    "A later {topic} stage anchors a model that already carries the domains before it.",
    "Held-out documents are scored after every epoch so the domain number is a measurement.",
)


def synthesize(directory: Path, topic: str, n_documents: int, n_sentences: int) -> Path:
    """Write ``n_documents`` filler documents about ``topic`` into ``directory``.

    Deterministic in ``topic`` and the counts, so re-running the example does not silently change
    the corpus underneath a workspace that was trained on it.
    """
    directory.mkdir(parents=True, exist_ok=True)
    for index in range(n_documents):
        rng = random.Random(f"{topic}/{index}")
        sentences = [rng.choice(_FRAMES).format(topic=topic) for _ in range(n_sentences)]
        text = f"# {topic} note {index}\n\n" + " ".join(sentences) + "\n"
        (directory / f"{topic}_{index:03d}.txt").write_text(text, encoding="utf-8")
    return directory


def materialise(spec_path: Path, out: Path, *, n_documents: int, n_sentences: int,
                epochs: int | None) -> Path:
    """Copy the spec into ``out``, generating a corpus for every domain that has none.

    A domain whose ``corpus`` already exists (resolved against the original spec, the way
    :meth:`lfa.Workspace.chain` resolves it) is left alone and used as it is -- so pointing the
    shipped spec at real documents makes this function a no-op.

    Returns:
        The path of the spec that should be run.
    """
    spec = yaml.safe_load(spec_path.read_text()) or {}
    domains = spec.get("domains")
    if not isinstance(domains, list) or not domains:
        raise ValueError(f"{spec_path}: a chain spec needs a non-empty 'domains' list.")

    for position, domain in enumerate(domains, start=1):
        if not isinstance(domain, dict) or not domain.get("corpus"):
            raise ValueError(f"{spec_path}: domain {position} has no 'corpus'.")
        name = domain.get("name") or Path(domain["corpus"]).name
        existing = (spec_path.parent / domain["corpus"]).expanduser()
        if existing.exists():
            domain["corpus"] = str(existing.resolve())
        else:
            generated = synthesize(out / "corpora" / name, name, n_documents, n_sentences)
            domain["corpus"] = str(generated.resolve())
            print(f"Generated {n_documents} filler documents for {name!r} in {generated}")
        if epochs is not None:
            domain["epochs"] = epochs

    out.mkdir(parents=True, exist_ok=True)
    materialised = out / "domains.yaml"
    materialised.write_text(yaml.safe_dump(spec, sort_keys=False))
    return materialised


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--model", required=True, help="a Hub id or a local checkpoint path")
    parser.add_argument("--artifact", default="qwen3-0.6b-gmm1543k-int8",
                        help="a published artifact id or a path to an artifact file "
                             "(default: %(default)s)")
    parser.add_argument("--artifact-id", dest="artifact_id",
                        help="the published id a locally-passed artifact FILE is a copy of")
    parser.add_argument("--out", required=True, help="directory for the corpora and the workspace")
    parser.add_argument("--spec", type=Path, default=DEFAULT_SPEC,
                        help="the chain spec to run (default: %(default)s)")
    parser.add_argument("--recipe",
                        help="a bundled recipe name or a path (default: the bundled recipe that "
                             "names this model, if there is one)")
    parser.add_argument("--epochs", type=int,
                        help="override every stage's epoch count -- for a smoke run; leave it "
                             "alone to use the spec's own")
    parser.add_argument("--documents", type=int, default=24, metavar="N",
                        help="filler documents per generated corpus (default: %(default)s)")
    parser.add_argument("--sentences", type=int, default=40, metavar="N",
                        help="filler sentences per generated document (default: %(default)s)")
    parser.add_argument("--device", default="cuda:0",
                        help="device to run on (default: %(default)s)")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    out = Path(args.out)
    spec = materialise(args.spec, out, n_documents=args.documents, n_sentences=args.sentences,
                       epochs=args.epochs)

    workspace = Workspace.init(out / "workspace", args.model, artifact=args.artifact,
                               artifact_id=args.artifact_id, recipe=args.recipe)
    entries = workspace.chain(spec, device=args.device)

    print(f"\n{len(entries)} stages trained:")
    for entry in entries:
        print(f"  stage {entry['stage']}  {Path(entry['corpus']).name:<20} "
              f"lambda {entry['lambda_applied']:<12g} artifact v{entry['artifact_version']}  "
              f"-> {entry['output_dir']}")
    history = out / "workspace" / "history.json"
    print(f"\nHistory ({len(json.loads(history.read_text()))} entries): {history}")
    print("Evaluate the last stage with: "
          f"lfa evaluate --workspace {out / 'workspace'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
